### ISSUE TITLE
No authentication mechanism in login

### ISSUE THREAD

**Issue by james-see** [marians/rebrow#16]
![screen shot 2016-10-06 at 2 51 23 pm](https://cloud.githubusercontent.com/assets/616585/19166184/994ef93a-8bd4-11e6-84c1-be283c1a7dff.png)
I have all my redisi set with passwords. Need to update the form to include the option to pass a password.

**Comment by crazywako** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/runserver.py", line 146, in server_db
    info = r.info("all")
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 667, in info
    return self.execute_command('INFO', section)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: NOAUTH Authentication required.

**Comment by earthgecko** [comment]
@jamesacampbell @crazywako there is a pull requests by @elky84
https://github.com/marians/rebrow/pull/20 that adds authentication and works.  However it sends the password in plaintext **and** adds it as a URL parameter.  In terms of localhost use of rebrow, you might find that acceptable.  However given the PRs current functionality I doubt whether @marians will merge it as it is totally insecure by default and really passing passwords in plaintext URL parameters is not what any developer should be aiming for in their application, whether it is intended for localhost use or not.

All that said I can confirm that PR #20 does work as it is but is **ONLY** suitable for localhost implementation.

**Comment by kveroneau** [comment]
I have created a similar PR #35 which passes the Redis password around via a session rather than in the URI.  I have tested this one against Azure's Cloud Redis server.

**Comment by james-see** [comment]
Cool
