### ISSUE TITLE
ascii codec cant decode byte

### ISSUE THREAD

**Issue by wessm** [marians/rebrow#21]
I am running the rebrow docker image. everything works, but as soon as I want to view a key, I get this error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/runserver.py", line 239, in key
    duration=time.time()-s)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/templates/key.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/app/templates/layout.html", line 66, in top-level template code
    {% block body %}{% endblock %}
  File "/app/templates/key.html", line 57, in block "body"
    <li><code>{{ item }}</code></li>
  File "/usr/local/lib/python2.7/site-packages/markupsafe/_native.py", line 22, in escape
    return Markup(text_type(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
```

Anyone knows what could be the problem? The key comes from huey, a python-based redis task scheduler.

**Comment by earthgecko** [comment]
Hi @wessm 

I while back I had a very similar issue with rebrow when I first implemented it as I store msgpack encoded values in my Redis keys.

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 0: ordinal not in range(128)
  File "/opt/redis-browser/github/redis-browser/redis_browser/templates/base.html", line 61, in block "data" 
    <tr><td>{{ loop.index }}</td><td>{{ value }}</td></tr>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 0: ordinal not in range(128)
192.168.1.22 - - [03/Jul/2016 09:11:39] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
```

In my case it was due to the key data in Redis being stored in a msgpack encoded string.  I do not think huey or peewee use msgpack, however I think you will find that it is related to the actually key value data encoding itself. I handled the msgpack issues as per https://github.com/earthgecko/skyline/blob/master/skyline/webapp/webapp.py#L2434

If you have a look at the offending key value/s themselves, I think you may find the issue there.  Also it may not be all you keys, only some that have a specific type of encoding.

**Comment by wessm** [comment]
Hi, thanks for your answer! I am new to all this, so I appreciate the help.
In redis-cli, I see that the key is of type `LIST` and looks like this:

```
127.0.0.1:6379> LRANGE huey.redis.other 0 -1
 1) "\x80\x03(X$\x00\x00\x002f36536e-3c51-46ce-b68c-1f4ad0d399dfq\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46RGR_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 2) "\x80\x03(X$\x00\x00\x00a16b3a93-95b1-4b63-8064-112c99cf74f5q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46RFR_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 3) "\x80\x03(X$\x00\x00\x0071d37c4a-ed3c-4863-88f4-5e88a6d2a5d6q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46RFQ_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 4) "\x80\x03(X$\x00\x00\x00299f5388-b69d-4124-a85c-cf64538608b3q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46REQ_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 5) "\x80\x03(X$\x00\x00\x008ffd72eb-4154-49b8-a97d-759a8f9c44dbq\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46REN_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 6) "\x80\x03(X$\x00\x00\x00003419bc-ed71-4a2f-a5d3-5e0d638fe7b3q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46RDP_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 7) "\x80\x03(X$\x00\x00\x002a1ffedd-31e2-4634-bba5-3032a7d95a01q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46RDN_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 8) "\x80\x03(X$\x00\x00\x009570471a-f4d1-4f12-b02d-0886261e76f7q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180109T042139_N0206_R090_T46RGR_20180109T144840.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
 9) "\x80\x03(X$\x00\x00\x001d1349cb-d86f-4fd0-a09b-cabc97fc4d88q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180109T042139_N0206_R090_T46RFR_20180109T144840.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
10) "\x80\x03(X$\x00\x00\x00fce6f14d-7a27-4179-88c0-42026e8b3a82q\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180109T042139_N0206_R090_T46RFQ_20180109T144840.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
11) "\x80\x03(X$\x00\x00\x00f7a996d2-4925-444e-9ba5-21d7b56abdddq\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180109T042139_N0206_R090_T46REQ_20180109T144840.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
12) "\x80\x03(X$\x00\x00\x003c624e2c-49ba-4c03-837d-a967d227a12dq\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180109T042139_N0206_R090_T46REN_20180109T144840.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
13) "\x80\x03(X$\x00\x00\x00c113e631-241d-4876-b2d4-9804d8e8d61cq\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180109T042139_N0206_R090_T46RDP_20180109T144840.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06."
127.0.0.1:6379> 


```

Apparently, thats how redis stores the tasks...any chance I can show that somehow woth rebrow?

**Comment by earthgecko** [comment]
@wessm 

huey is using pickle (in your case specifically Python 3 pickle), from https://docs.python.org/3/library/pickle.html

> The pickle module implements binary protocols for serializing and de-serializing a Python object structure. “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a byte stream (from a binary file or bytes-like object) is converted back into an object hierarchy. Pickling (and unpickling) is alternatively known as “serialization”, “marshalling,” or “flattening”; however, to avoid confusion, the terms used here are “pickling” and “unpickling”.

So if we unpickle one of your examples from above.

```python
>>> huey_pickled_key = b'\x80\x03(X$\x00\x00\x002f36536e-3c51-46ce-b68c-1f4ad0d399dfq\x00X\x13\x00\x00\x00queue_task_makeTifsq\x01NK\x00K\x00XA\x00\x00\x00S2B_MSIL2A_20180320T041539_N0206_R090_T46RGR_20180320T075628.SAFEq\x02\x85q\x03}q\x04\x86q\x05Ntq\x06.'
>>> import pickle
>>> huey_unpickled_key = pickle.loads(huey_pickled_key)
>>> huey_unpickled_key
('2f36536e-3c51-46ce-b68c-1f4ad0d399df', 'queue_task_makeTifs', None, 0, 0, (('S2B_MSIL2A_20180320T041539_N0206_R090_T46RGR_20180320T075628.SAFE',), {}), None)
>>>
```

rebrow will not handle this natively, however it would be possible for you to fork rebrow and with some tinkering you could get it to work.

**Comment by wessm** [comment]
Hi @earthgecko 
Thanks for pointing me to pickle! I made quite an amateurish [fork](https://github.com/wessm/rebrow) of the repo and made it work! I had to switch to python3 to get pickle working, and I added various `encode()`s and `decode()`s all over the place to overcome some byte/string problem, but now I finally can see my huey tasks in the browser! perfect!
