### ISSUE TITLE
Can't view hash type

### ISSUE THREAD

**Issue by dasjestyr** [marians/rebrow#29]
Whenever I click on a hash, I get a generic server error. Are hashes not supported?

**Comment by earthgecko** [comment]
Hi @dasjestyr it seems that it does support the hash Redis data type:
* https://github.com/marians/rebrow/search?q=hash&type=Code
* https://github.com/marians/rebrow/blob/b12fdbfbfd4e839ed8f5c7bf41889277f6859077/runserver.py#L222

In terms of the generic server error, are you implying that the server error is `Can't view hash type`?
Although that does not appear to be a string in rebrow, so could you post any traceback that you receive and the output of ```pip list | grep "redis\|Flask"``` and the version of Redis you are running and the version of rebrow you are running.

**Comment by dasjestyr** [comment]
There's no error message other than a generic 500 message. I'm running from the latest docker image, so whatever is running on there is what I have. Redis version is also a docker image redis:latest

**Comment by earthgecko** [comment]
@dasjestyr there will be, you just need to issue the following command to see docker logs

```bash
docker logs <CONTAINER_ID>
```

Where CONTAINER_ID is the ID of your marian/rebrow container.  That will show you the log of the rebrow app e.g.

```
$ docker logs 82616573cb242578952b710df76f7c72d7ee45a7ba63a97aaf9d5905581c6fbd
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
172.17.0.1 - - [10/Oct/2018 16:15:25] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [10/Oct/2018 16:15:27] "POST / HTTP/1.1" 302 -
[2018-10-10 16:15:27,356] ERROR in app: Exception on /localhost:6379/0/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/runserver.py", line 146, in server_db
    info = r.info("all")
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 667, in info
    return self.execute_command('INFO', section)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 99 connecting to localhost:6379. Address not available.
172.17.0.1 - - [10/Oct/2018 16:15:27] "GET /localhost:6379/0/ HTTP/1.1" 500 -
```

**Comment by dasjestyr** [comment]
Huh... interesting. I had deleted it and moved over to using redis-commander, but in effort to get that log, I pulled it back down and ran it again and I'm not getting the error anymore. Strange... 

thanks
