### ISSUE TITLE
cannot search keys

### ISSUE THREAD

**Issue by zinnov-manu** [marians/rebrow#30]
Unable to view data or search keys after a successful connection

**Comment by ManyEyedFox** [comment]
same problem here
  File "runserver.py", line 274, in urlsafe_base64_encode
    s = s.encode('utf8')
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by zinnov-manu** [comment]
> same problem here
> File "runserver.py", line 274, in urlsafe_base64_encode
> s = s.encode('utf8')
> AttributeError: 'bytes' object has no attribute 'encode'

Could you check the type of the variable 's' and ensure it has an encode method available in the python version you are using.

**Comment by marians** [comment]
Could you please provide these details:

- What redis version are you using?
- What steps exactly are you taking in order to reproduce the result?

**Comment by eternioc** [comment]
I have the same problem. My redis seems to contain bytes string keys, which don't have an encode attribute. 

As a quick fix, I added an exception handler in runserver.py's urlsafe_base64_encode(s) function:
```
def urlsafe_base64_encode(s):
    try:
        if type(s) == 'Markup':
            s = s.unescape()
        s = s.encode('utf8')
    except(AttributeError):
        pass
    s = base64.urlsafe_b64encode(s)
    return Markup(s)
```
This way all the keys show up, yay!

You cannot inspect them yet. If you click the keys, they are either not found or they are incorrectly transformed. I guess the handling of bytes keys has to be also adjusted elsewhere, but the stack trace gives me no hint:
```
[2020-04-07 11:30:11,160] ERROR in app: Exception on /localhost:6379/0/keys/b'YXNnaTo6Z3JvdXA6bm90aWZpY2F0aW9uc19jaGFubmVsX2dyb3Vw'/ [GET]
Traceback (most recent call last):
  File "C:\Tools\rebrow\venv\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Tools\rebrow\venv\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Tools\rebrow\venv\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Tools\rebrow\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Tools\rebrow\venv\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Tools\rebrow\venv\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "runserver.py", line 205, in key
    """
  File "C:\Program Files\Python36\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Program Files\Python36\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
I am using redis 2.8 and python 3.6 by the way.
